import React from 'react';
import { View, Text, StyleSheet, FlatList, Dimensions, SafeAreaView, TouchableOpacity } from 'react-native';
import { WebView } from 'react-native-webview';
import { RootStackScreenProps } from '../navigation/types';
import { Game } from '../types/entities';
import Icon from 'react-native-vector-icons/Ionicons';

const { height } = Dimensions.get('window');

const GameReelsScreen = ({ route, navigation }: RootStackScreenProps<'GameReels'>) => {
  const { games, initialGameId } = route.params;

  const initialIndex = games.findIndex(game => game.id === initialGameId);

  const renderItem = ({ item }: { item: Game }) => (
    <View style={styles.page}>
      <WebView
        originWhitelist={['*']}
        source={{
          html: item.gameHtml || `<html><body><h1>No Game HTML</h1><p>This game was not generated by AI.</p></body></html>`,
          baseUrl: '', // baseUrl is required for html source on some platforms
        }}
        style={styles.webview}
        javaScriptEnabled
        scrollEnabled={false} // Disable webview scrolling
      />
      <TouchableOpacity style={styles.closeButton} onPress={() => navigation.goBack()}>
        <Icon name="close" size={30} color="#fff" />
      </TouchableOpacity>
    </View>
  );

  return (
    <SafeAreaView style={styles.container}>
      <FlatList
        data={games}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        pagingEnabled
        showsVerticalScrollIndicator={false}
        initialScrollIndex={initialIndex >= 0 ? initialIndex : 0}
        getItemLayout={(data, index) => (
          { length: height, offset: height * index, index }
        )}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  page: {
    width: '100%',
    height: height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  webview: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1,
  }
});

export default GameReelsScreen;
